# Generated by Django 2.1.7 on 2019-04-25 21:36

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='MyGroups',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='MyUsers',
        ),
    ]
